name: body_detection
description: A flutter plugin that uses MLKit on iOS/Android platforms to enable body pose and mask detection using Pose Detection and Selfie Segmentation APIs for both static images and live camera stream.
version: 0.0.3
homepage: https://0x48lab.com
repository: https://github.com/0x48lab/flutter_body_detection

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.u0x48lab.body_detection
        pluginClass: BodyDetectionPlugin
      ios:
        pluginClass: BodyDetectionPlugin

